# templates/app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-app
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/component: frontend
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook
        tier: frontend
        app.kubernetes.io/name: guestbook
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: "1.0"
        app.kubernetes.io/component: frontend
        monitoring: "false"
        logging: "true"
    spec:
      initContainers:
      - name: wait-db
        image: busybox
        command: ['sh', '-c', 'until nc -z service-postgres 5432; do sleep 2; done']

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: guestbook
              topologyKey: kubernetes.io/hostname

      containers:
      - name: guestbook
        image: azubeq/app-guestbook:{{ .Values.appVersion }}
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | quote }}
            cpu: {{ .Values.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.resources.limits.memory | quote }}
            cpu: {{ .Values.resources.limits.cpu | quote }}
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        envFrom:
        - configMapRef:
            name: app-config
        readinessProbe:
          httpGet:
            path: /  # Или специальный эндпоинт /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 20

---
# templates/app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: service-guestbook
  namespace: {{ .Release.Namespace }}
  labels:
    app: guestbook
    tier: frontend
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend    
spec:
  type: {{ .Values.serviceType }}
  selector: # find POD's
    app: guestbook
    tier: frontend
  ports:
    - port: 80
      targetPort: 5000